import path from 'node:path';

import {
    ensureDirectory,
    resolveOutputPath,
    writeBinaryFile,
    writeTextFile,
} from './files.js';
import { finalizeImage } from './image.js';

/** @typedef {import('playwright').Page} Page */
/** @typedef {import('./image.js').QuantizeRect} QuantizeRect */
/** @typedef {import('./progress.js').ProgressReporter} ProgressReporter */

/**
 * A plain-text file generated by the capture tool.
 *
 * @typedef {object} CaptureTextFile
 * @property {string} filename Destination path relative to the language-pack root.
 * @property {undefined} [dataType]
 * @property {string} contents Text contents.
 */

/**
 * A binary file referenced by URL.
 *
 * @typedef {object} CaptureUrlFile
 * @property {string} filename Destination path relative to the language-pack root.
 * @property {'url'} dataType
 * @property {string} contents Resource URL.
 */

/**
 * A binary file embedded as a base64 data URL.
 *
 * @typedef {object} CaptureDataUrlFile
 * @property {string} filename Destination path relative to the language-pack root.
 * @property {'dataURL'} dataType
 * @property {string} contents Base64 data URL.
 */

/**
 * @typedef {CaptureTextFile | CaptureUrlFile | CaptureDataUrlFile} CaptureDataFile
 */

/**
 * Description of an image rendered by the localization tool.
 *
 * @typedef {object} CaptureImage
 * @property {string} id DOM identifier of the capture element.
 * @property {string} filename Destination path relative to the language-pack root.
 * @property {number} w Logical image width.
 * @property {number} h Logical image height.
 * @property {QuantizeRect[]} quantizeRects Regions requiring palette quantization.
 * @property {boolean} wantAutoCrop Whether transparent borders should be cropped.
 * @property {boolean} baked Whether the image comes from baked game resources.
 */

/**
 * @typedef {object} CaptureLoadResult
 * @property {string=} error Error reported while importing the localization.
 */

/**
 * @typedef {object} CaptureBeginResult
 * @property {string=} error Error reported while preparing the capture.
 * @property {string} lang Language identifier.
 * @property {CaptureImage[]} images Images to capture.
 * @property {CaptureDataFile[]} dataFiles Additional files to write.
 */

/**
 * Browser-side capture API exposed by the localization tool.
 *
 * @typedef {object} CaptureApi
 * @property {(csv: string) => CaptureLoadResult} load
 * @property {(scale: number, makeFonts: boolean) => CaptureBeginResult} begin
 * @property {(imageId: string) => void} isolate
 */

/**
 * @typedef {typeof globalThis & {
 *     $: {
 *         capture: CaptureApi,
 *     },
 * }} CaptureGlobal
 */

/**
 * @typedef {object} CaptureOptions
 * @property {Page} page Playwright page containing the localization tool.
 * @property {<T>(operation: () => Promise<T>) => Promise<T>} runAndWaitForIdle
 *     Runs an operation and waits for browser resources to become idle.
 * @property {number} scale Capture scale applied by the web application.
 * @property {boolean} makeFonts Whether bitmap-font assets should be generated.
 * @property {string} outputDir Language-pack output directory.
 * @property {string} csv Contents of Loc.csv.
 * @property {ProgressReporter} progress Progress reporter.
 */

/**
 * Imports a localization into the browser-side capture tool.
 *
 * @param {Page} page
 * @param {string} csv
 * @returns {Promise<CaptureLoadResult>}
 */
async function loadLocalization(page, csv) {
    return /** @type {CaptureLoadResult} */ (
        await page.evaluate((contents) => {
            const browser = /** @type {CaptureGlobal} */ (globalThis);

            return browser.$.capture.load(contents);
        }, csv)
    );
}

/**
 * Prepares the localized page for capture.
 *
 * The browser-side implementation also applies the requested CSS zoom used
 * when rasterizing game assets.
 *
 * @param {Page} page
 * @param {number} scale
 * @param {boolean} makeFonts
 * @returns {Promise<CaptureBeginResult>}
 */
async function beginCapture(page, scale, makeFonts) {
    return /** @type {CaptureBeginResult} */ (
        await page.evaluate((options) => {
            const browser = /** @type {CaptureGlobal} */ (globalThis);

            return browser.$.capture.begin(
                options.scale,
                options.makeFonts,
            );
        }, { scale, makeFonts })
    );
}

/**
 * Moves a capture element into the browser-side capture position.
 *
 * The original renderer relies on this before taking a fixed-size screenshot.
 *
 * @param {Page} page
 * @param {string} imageId
 * @returns {Promise<void>}
 */
async function isolateCapture(page, imageId) {
    await page.evaluate((id) => {
        const browser = /** @type {CaptureGlobal} */ (globalThis);

        browser.$.capture.isolate(id);
    }, imageId);
}

/**
 * Downloads a resource using Playwright's request context.
 *
 * Unlike fetching inside `page.evaluate()`, this returns the response body
 * directly as a Node.js Buffer without serializing every byte through the
 * browser boundary.
 *
 * @param {Page} page
 * @param {string} url
 * @returns {Promise<Buffer>}
 */
async function fetchResource(page, url) {
    const resourceUrl = new URL(url, page.url()).href;
    const response = await page.request.get(resourceUrl);

    try {
        if (!response.ok()) {
            throw new Error(
                `Failed to fetch ${resourceUrl}: `
                + `${response.status()} ${response.statusText()}`,
            );
        }

        return await response.body();
    } finally {
        await response.dispose();
    }
}

/**
 * Decodes a base64 data URL.
 *
 * @param {string} dataUrl
 * @returns {Buffer}
 */
function decodeDataUrl(dataUrl) {
    const match = /^data:[^,]*;base64,(.*)$/s.exec(dataUrl);

    if (!match) {
        throw new Error('Unsupported data URL');
    }

    return Buffer.from(match[1], 'base64');
}

/**
 * Writes a file produced by the browser-side capture tool.
 *
 * @param {Page} page
 * @param {string} outputDir
 * @param {CaptureDataFile} dataFile
 * @returns {Promise<void>}
 */
async function writeDataFile(page, outputDir, dataFile) {
    const {
        filename: relativeFilename,
        dataType,
    } = dataFile;

    const filename = resolveOutputPath(
        outputDir,
        relativeFilename,
    );

    switch (dataType) {
        case undefined:
            await writeTextFile(
                filename,
                dataFile.contents,
            );
            break;

        case 'url':
            await writeBinaryFile(
                filename,
                await fetchResource(page, dataFile.contents),
            );
            break;

        case 'dataURL':
            await writeBinaryFile(
                filename,
                decodeDataUrl(dataFile.contents),
            );
            break;

        default:
            throw new Error(
                `Unsupported data type for ${relativeFilename}: `
                + String(dataType),
            );
    }
}

/**
 * Captures one rendered game asset and performs its final image processing.
 *
 * The dimensions returned by `$.capture.begin()` are the authoritative logical
 * dimensions of the asset. The renderer uses CSS `zoom`, so the screenshot is
 * clipped explicitly to `scale * width` by `scale * height` rather than using
 * Playwright's inferred element bounds.
 *
 * @param {Page} page
 * @param {number} scale
 * @param {string} outputDir
 * @param {CaptureImage} image
 * @returns {Promise<void>}
 */
async function captureImage(
    page,
    scale,
    outputDir,
    image,
) {
    const filename = resolveOutputPath(
        outputDir,
        image.filename,
    );

    await ensureDirectory(path.dirname(filename));
    await isolateCapture(page, image.id);

    await page.screenshot({
        path: filename,
        clip: {
            x: 0,
            y: 0,
            width: scale * image.w,
            height: scale * image.h,
        },
        omitBackground: true,
    });

    await finalizeImage(
        filename,
        image.w,
        image.h,
        image.quantizeRects,
        image.wantAutoCrop,
    );
}

/**
 * Generates a complete localization package.
 *
 * The web application owns localization and rendering. This function drives
 * that renderer through Playwright, writes its generated files, captures image
 * assets, and performs the required image post-processing.
 *
 * @param {CaptureOptions} options
 * @returns {Promise<string>} Language identifier reported by the capture tool.
 */
export async function capture({
    page,
    runAndWaitForIdle,
    scale,
    makeFonts,
    outputDir,
    csv,
    progress,
}) {
    progress.log('Preparing page');

    const load = await runAndWaitForIdle(
        () => loadLocalization(page, csv),
    );

    if (load.error) {
        throw new Error(load.error);
    }

    const result = await beginCapture(
        page,
        scale,
        makeFonts,
    );

    if (result.error) {
        throw new Error(result.error);
    }

    const {
        lang,
        images,
        dataFiles,
    } = result;

    progress.log(`Language: ${lang}`);
    progress.log(
        `Packing ${images.length} images `
        + `and ${dataFiles.length} data files`,
    );

    const dataProgress = progress.createTask(
        'Data',
        dataFiles.length,
    );

    for (const dataFile of dataFiles) {
        dataProgress.start(dataFile.filename);

        await writeDataFile(
            page,
            outputDir,
            dataFile,
        );

        dataProgress.complete();
    }

    const imageProgress = progress.createTask(
        'Image',
        images.length,
    );

    // Each capture mutates the shared browser DOM through `isolate()`.
    for (const image of images) {
        const flags = [
            image.quantizeRects.length > 0 && 'PAL',
            image.baked && 'BAKED',
        ].filter(Boolean).join(' ');

        imageProgress.start(
            `${image.filename} (${image.w}x${image.h})`
            + (flags ? ` ${flags}` : ''),
        );

        await captureImage(
            page,
            scale,
            outputDir,
            image,
        );

        imageProgress.complete();
    }

    return lang;
}
