import path from 'node:path';

import {
    ensureDirectory,
    resolveOutputPath,
    writeBinaryFile,
    writeTextFile,
} from './files.js';
import { finalizeImage } from './image.js';

/** @typedef {import('playwright').Page} Page */
/** @typedef {import('./image.js').QuantizeRect} QuantizeRect */
/** @typedef {import('./progress.js').ProgressReporter} ProgressReporter */

/**
 * A plain-text file generated by the capture tool.
 *
 * @typedef {object} CaptureTextFile
 * @property {string} filename Destination path relative to the language-pack root.
 * @property {undefined} [dataType]
 * @property {string} contents Text contents.
 */

/**
 * A binary file that must be downloaded from a URL.
 *
 * @typedef {object} CaptureUrlFile
 * @property {string} filename Destination path relative to the language-pack root.
 * @property {'url'} dataType
 * @property {string} contents Resource URL.
 */

/**
 * A binary file embedded as a base64 data URL.
 *
 * @typedef {object} CaptureDataUrlFile
 * @property {string} filename Destination path relative to the language-pack root.
 * @property {'dataURL'} dataType
 * @property {string} contents Base64 data URL.
 */

/**
 * @typedef {CaptureTextFile | CaptureUrlFile | CaptureDataUrlFile} CaptureDataFile
 */

/**
 * Description of an image rendered by the localization tool.
 *
 * @typedef {object} CaptureImage
 * @property {string} id DOM identifier of the capture element.
 * @property {string} filename Destination path relative to the language-pack root.
 * @property {number} w Logical image width before capture scaling.
 * @property {number} h Logical image height before capture scaling.
 * @property {QuantizeRect[]} quantizeRects Regions that require palette quantization.
 * @property {boolean} wantAutoCrop Whether transparent borders should be cropped.
 * @property {boolean} baked Whether the image comes from baked resources.
 */

/**
 * @typedef {object} CaptureLoadResult
 * @property {string=} error Error reported while importing the localization.
 */

/**
 * @typedef {object} CaptureBeginResult
 * @property {string} lang Language identifier.
 * @property {CaptureImage[]} images Images to capture.
 * @property {CaptureDataFile[]} dataFiles Additional files to write.
 */

/**
 * Browser-side capture API exposed by the localization tool.
 *
 * @typedef {object} CaptureApi
 * @property {(csv: string) => CaptureLoadResult} load
 * @property {(scale: number, makeFonts: boolean) => CaptureBeginResult} begin
 */

/**
 * @typedef {typeof globalThis & {
 *     $: {
 *         capture: CaptureApi,
 *     },
 * }} CaptureGlobal
 */

/**
 * @typedef {object} CaptureOptions
 * @property {Page} page Playwright page containing the localization tool.
 * @property {<T>(operation: () => Promise<T>) => Promise<T>} runAndWaitForIdle
 *     Runs an operation and waits for browser resources to become idle.
 * @property {number} scale Capture scale applied by the web application.
 * @property {boolean} makeFonts Whether bitmap-font assets should be generated.
 * @property {string} outputDir Language-pack output directory.
 * @property {string} csv Contents of the input Loc.csv file.
 * @property {ProgressReporter} progress Progress reporter.
 */

/**
 * Imports a localization into the browser-side capture tool.
 *
 * @param {Page} page Playwright page containing the localization tool.
 * @param {string} csv Contents of Loc.csv.
 * @returns {Promise<CaptureLoadResult>}
 */
async function loadLocalization(page, csv) {
    return /** @type {CaptureLoadResult} */ (
        await page.evaluate((contents) => {
            const browser = /** @type {CaptureGlobal} */ (globalThis);

            return browser.$.capture.load(contents);
        }, csv)
    );
}

/**
 * Prepares the page for capture and retrieves the generated asset metadata.
 *
 * `begin()` also applies the requested CSS capture scale to the page.
 *
 * @param {Page} page Playwright page containing the localization tool.
 * @param {number} scale Capture scale.
 * @param {boolean} makeFonts Whether bitmap fonts should be generated.
 * @returns {Promise<CaptureBeginResult>}
 */
async function beginCapture(page, scale, makeFonts) {
    return /** @type {CaptureBeginResult} */ (
        await page.evaluate((options) => {
            const browser = /** @type {CaptureGlobal} */ (globalThis);

            return browser.$.capture.begin(
                options.scale,
                options.makeFonts,
            );
        }, { scale, makeFonts })
    );
}

/**
 * Downloads a resource using Playwright's request context.
 *
 * The request context shares cookies with the page's BrowserContext, while
 * returning the response body directly as a Node.js Buffer.
 *
 * @param {Page} page Playwright page containing the localization tool.
 * @param {string} url Resource URL, absolute or relative to the current page.
 * @returns {Promise<Buffer>} Resource contents.
 */
async function fetchResource(page, url) {
    const resourceUrl = new URL(url, page.url()).href;
    const response = await page.request.get(resourceUrl);

    try {
        if (!response.ok()) {
            throw new Error(
                `Failed to fetch ${resourceUrl}: `
                + `${response.status()} ${response.statusText()}`,
            );
        }

        return await response.body();
    } finally {
        await response.dispose();
    }
}

/**
 * Decodes a base64 data URL.
 *
 * @param {string} dataUrl Base64 data URL.
 * @returns {Buffer} Decoded contents.
 */
function decodeDataUrl(dataUrl) {
    const match = /^data:[^,]*;base64,(.*)$/s.exec(dataUrl);

    if (!match) {
        throw new Error('Unsupported data URL');
    }

    return Buffer.from(match[1], 'base64');
}

/**
 * Writes a file produced by the browser-side capture tool.
 *
 * @param {Page} page Playwright page containing the localization tool.
 * @param {string} outputDir Language-pack output directory.
 * @param {CaptureDataFile} dataFile Generated file description.
 * @returns {Promise<void>}
 */
async function writeDataFile(page, outputDir, dataFile) {
    const filename = resolveOutputPath(
        outputDir,
        dataFile.filename,
    );

    switch (dataFile.dataType) {
        case 'url':
            await writeBinaryFile(
                filename,
                await fetchResource(page, dataFile.contents),
            );
            return;

        case 'dataURL':
            await writeBinaryFile(
                filename,
                decodeDataUrl(dataFile.contents),
            );
            return;

        default:
            await writeTextFile(
                filename,
                dataFile.contents,
            );
    }
}

/**
 * Captures one rendered image and performs its final image processing.
 *
 * The web application has already applied `scale` through its CSS zoom before
 * this function is called. Playwright therefore captures the element at its
 * rendered dimensions rather than requiring a manually scaled clip rectangle.
 *
 * @param {Page} page Playwright page containing the localization tool.
 * @param {string} outputDir Language-pack output directory.
 * @param {CaptureImage} image Image description.
 * @returns {Promise<void>}
 */
async function captureImage(page, outputDir, image) {
    const filename = resolveOutputPath(
        outputDir,
        image.filename,
    );

    await ensureDirectory(path.dirname(filename));

    await page.locator(`#${image.id}.capture`).screenshot({
        path: filename,
        omitBackground: true,
        scale: 'css',
    });

    await finalizeImage(
        filename,
        image.w,
        image.h,
        image.quantizeRects,
        image.wantAutoCrop,
    );
}

/**
 * Generates a complete Papers, Please localization package.
 *
 * The browser owns localization and rendering. The packer imports Loc.csv, asks
 * the browser for the assets that need to be generated, persists its data
 * files, captures its rendered images, and runs the required image
 * post-processing.
 *
 * @param {CaptureOptions} options Capture configuration.
 * @returns {Promise<string>} Language identifier reported by the capture tool.
 */
export async function capture({
    page,
    runAndWaitForIdle,
    scale,
    makeFonts,
    outputDir,
    csv,
    progress,
}) {
    progress.log('Preparing page');

    /*
     * Importing the localization can start asynchronous requests for baked
     * images, fonts, and other resources. Wait until they have settled before
     * asking the page which assets need to be captured.
     */
    const load = await runAndWaitForIdle(
        () => loadLocalization(page, csv),
    );

    if (load.error) {
        throw new Error(load.error);
    }

    const {
        lang,
        images,
        dataFiles,
    } = await beginCapture(
        page,
        scale,
        makeFonts,
    );

    progress.log(`Language: ${lang}`);
    progress.log(
        `Packing ${images.length} images `
        + `and ${dataFiles.length} data files`,
    );

    const dataProgress = progress.createTask(
        'Data',
        dataFiles.length,
    );

    for (const dataFile of dataFiles) {
        dataProgress.start(dataFile.filename);

        await writeDataFile(
            page,
            outputDir,
            dataFile,
        );

        dataProgress.complete();
    }

    const imageProgress = progress.createTask(
        'Image',
        images.length,
    );

    /*
     * Keep captures sequential. Every image is rendered from the same page and
     * therefore shares the same DOM and rendering state.
     */
    for (const image of images) {
        const flags = [
            image.quantizeRects.length > 0 && 'PAL',
            image.baked && 'BAKED',
        ].filter(Boolean).join(' ');

        imageProgress.start(
            `${image.filename} (${image.w}x${image.h})`
            + (flags ? ` ${flags}` : ''),
        );

        await captureImage(
            page,
            outputDir,
            image,
        );

        imageProgress.complete();
    }

    return lang;
}
